[package]
name = "cdp"
version = "0.3.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["process", "io-util", "sync", "time", "net", "rt", "macros"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
futures-util = "0.3"
tracing = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
anyhow = { workspace = true }
bytes = "1"

[lints]
workspace = true
